local R, C, L, DB = unpack(select(2, ...))

local function LoadSkin()
	R.SetBD(ReforgingFrame)
	select(12,ReforgingFrameItemButton:GetRegions()):Hide()
	ReforgingFrame:DisableDrawLayer("BACKGROUND")
	ReforgingFrame:DisableDrawLayer("BORDER")
	ReforgingFramePortrait:Hide()
	ReforgingFrameBg:Hide()
	ReforgingFrameTitleBg:Hide()
	ReforgingFramePortraitFrame:Hide()
	ReforgingFrameTopBorder:Hide()
	ReforgingFrameTopRightCorner:Hide()
	ReforgingFrameRestoreButton_LeftSeparator:Hide()
	ReforgingFrameRestoreButton_RightSeparator:Hide()
	ReforgingFrameButtonFrame:GetRegions():Hide()
	ReforgingFrameButtonFrameButtonBorder:Hide()
	ReforgingFrameButtonFrameButtonBottomBorder:Hide()
	ReforgingFrameButtonFrameMoneyLeft:Hide()
	ReforgingFrameButtonFrameMoneyRight:Hide()
	ReforgingFrameButtonFrameMoneyMiddle:Hide()
	ReforgingFrameRestoreMessage:SetTextColor(1, 1, 1)
	R.Reskin(ReforgingFrameRestoreButton)
	R.Reskin(ReforgingFrameReforgeButton)
	R.ReskinClose(ReforgingFrameCloseButton)
	ReforgingFrameRestoreButton:ClearAllPoints()
	ReforgingFrameRestoreButton:SetPoint("LEFT", ReforgingFrameMoneyFrame, "RIGHT", 60, 0)
	ReforgingFrameReforgeButton:ClearAllPoints()
	ReforgingFrameReforgeButton:SetPoint("LEFT", ReforgingFrameRestoreButton, "RIGHT", 1, 0)
end

R.SkinFuncs["Blizzard_ReforgingUI"] = LoadSkin