local R, C, L, DB = unpack(select(2, ...))

local Skin = CreateFrame("Frame", nil, UIParent)
Skin:RegisterEvent("ADDON_LOADED")
Skin:SetScript("OnEvent", function(self, event, addon)
	if addon == "Clique" then
		local tab = _G["CliqueSpellTab"]
		tab:GetRegions():Hide()
		tab:SetCheckedTexture(R.checked)
		tab:GetNormalTexture():SetTexCoord(.08, .92, .08, .92)
		R.CreateBG(tab)
		R.CreateSD(tab, 5, 0, 0, 0, 1, 1)
		select(4, tab:GetRegions()):SetTexCoord(.08, .92, .08, .92)
		CliqueConfig:StripTextures()
		CliqueConfigInset:StripTextures()
		R.SetBD(CliqueConfig)
		CliqueConfigPage1Column1:DisableDrawLayer("BACKGROUND")
		CliqueConfigPage1Column2:DisableDrawLayer("BACKGROUND")
		R.ReskinClose(CliqueConfigCloseButton)
		R.Reskin(CliqueConfigPage1ButtonSpell)
		CliqueConfigPage1ButtonSpell_RightSeparator:Kill()
		R.Reskin(CliqueConfigPage1ButtonOther)
		CliqueConfigPage1ButtonOther_RightSeparator:Kill()
		R.Reskin(CliqueConfigPage1ButtonOptions)
		CliqueConfigPage1ButtonOptions_LeftSeparator:Kill()
	end
end)